#!/bin/bash

if [ "$1" == 'swap' ]; then
    if [ "$(id -u)" != "0" ]; then
       echo "This script must be run as root" 1>&2
       exit 1
    fi
    swap=`cat /proc/meminfo | grep MemTotal | awk '{print $2}'`
    cd /var
    mount -o remount,rw /
    dd if=/dev/zero of=/var/swap bs=1024 count=$[$swap*2]
    chmod 600 swap
    mkswap swap
    swapon /var/swap
    echo 'start on started boot-services' > /etc/init/swap.conf
    echo 'stop on stopping boot-services' >> /etc/init/swap.conf
    echo 'script' >> /etc/init/swap.conf
    echo 'swapon /var/swap' >> /etc/init/swap.conf
    echo 'end script' >> /etc/init/swap.conf
fi
if [ "$1" == 'ubuntu' ]; then
    if [ "$(id -u)" != "0" ]; then
       echo "This script must be run as root" 1>&2
       exit 1
    fi
    mkdir /tmp/chromeos
    cd /tmp/chromeos
    wget https://raw.githubusercontent.com/dnschneid/crouton/master/installer/crouton
    sh crouton -r trusty -t xfce
fi
if [ "$1" == 'aria2' ]; then
    if [ "$(id -u)" != "0" ]; then
       echo "This script must be run as root" 1>&2
       exit 1
    fi
    mkdir /tmp/chromeos
    cd /tmp/chromeos
    wget https://github.com/clamsawd/aria2-static-builds/releases/download/v1.20.0/aria2-1.20.0-linux-gnu-32bit-build1.tar.bz2 -O aria2.tar.bz2
    mount -o remount,rw /
    tar xvf aria2.tar.bz2 -C /
    rm -r /tmp/chromeos
fi
if [ "$1" == 'server' ]; then
    if [ "$(id -u)" != "0" ]; then
       echo "This script must be run as root" 1>&2
       exit 1
    fi
    mkdir /tmp/chromeos
    cd /tmp/chromeos
    mount -o remount,rw /
    wget https://github.com/roulis2844sasha/chromeos/raw/master/php/chromeos
    #cp php_x86 /usr/bin/server
    #cp libmcrypt.so.4 /usr/lib/libmcrypt.so.4
    rm -r /tmp/chromeos
fi
if [ "$1" == 'usb' ]; then
    if [ -f "/usr/bin/unzip" ]; then
        mkdir /tmp/chromeos
        cd /tmp/chromeos
        wget http://go.neverware.com/free -O chromiumos.bin.zip
        unzip chromiumos.bin.zip
    fi
fi
if [ ! "$1" ]; then
    echo 'help'
    echo 'bash chromeos swap - create swap file'
    echo 'bash chromeos ubuntu - install ubuntu'
    echo 'bash chromeos aria2 - install aria2'
    echo 'bash chromeos server - install web server'
    #echo 'bash chromeos usb - create ChromiumOS LiveUSB'
fi
